services:
  olveneer.normalizer:
    class: Olveneer\DataProcessorBundle\DataClass\Normalizer
    arguments: ['@serializer.property_accessor']

  olveneer.api_point_handler:
    class: Olveneer\DataProcessorBundle\Api\ApiPointHandler
    arguments: ['@olveneer.normalizer', '@doctrine.orm.entity_manager', '@validator', '@request_stack', '@translator']

  Olveneer\DataProcessorBundle\Api\ApiPointHandler:           '@olveneer.api_point_handler'
  Olveneer\DataProcessorBundle\DataClass\Normalizer:          '@olveneer.normalizer'